@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor Actor
participant AverageYearlyIncreaseInteractor
database TwelveDataAPI
entity Stock
entity StockPrice
participant AverageYearlyIncreaseOutputData
boundary AverageYearlyIncreaseOutputBoundary


Actor -> AverageYearlyIncreaseInteractor : execute
AverageYearlyIncreaseInteractor -> TwelveDataAPI : symbolExists
TwelveDataAPI --> AverageYearlyIncreaseInteractor
AverageYearlyIncreaseInteractor -> TwelveDataAPI : getHistoricalPrice
TwelveDataAPI --> AverageYearlyIncreaseInteractor
TwelveDataAPI -> Stock : createStock
Stock -> StockPrice : createPrice
Stock --> AverageYearlyIncreaseInteractor
AverageYearlyIncreaseInteractor -> AverageYearlyIncreaseOutputData : create
AverageYearlyIncreaseOutputData --> AverageYearlyIncreaseInteractor
AverageYearlyIncreaseInteractor -> AverageYearlyIncreaseOutputBoundary : prepareGraphicalView
AverageYearlyIncreaseOutputBoundary --> AverageYearlyIncreaseInteractor
AverageYearlyIncreaseInteractor -> AverageYearlyIncreaseOutputBoundary : prepareTabularView
AverageYearlyIncreaseOutputBoundary --> AverageYearlyIncreaseInteractor
AverageYearlyIncreaseInteractor --> Actor
@enduml